CREATE TABLE COMPANY
(
    ID           INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DENOMINATION TEXT            NOT NULL,
    AGE          INT             NOT NULL,
    ADDRESS      CHAR(50),
    SALARY       REAL
);

INSERT INTO COMPANY (DENOMINATION, AGE, ADDRESS, SALARY)
VALUES ('Test Ltd', 42, 'Ping Road 22', 25000.7);